# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrainer', '0003_auto_20181021_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('symbol', models.CharField(default='', max_length=100)),
                ('exchange_rate', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_annual_eps',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_annual_net_income',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_annual_revenue',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_annual_total_assets',
        ),
    ]
