# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrainer', '0003_auto_20181021_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_annual_eps',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_annual_net_income',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_annual_revenue',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_annual_total_assets',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='website',
        ),
        migrations.AddField(
            model_name='stock',
            name='history',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AddField(
            model_name='stock',
            name='prediction',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='region',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='sentiment',
            field=models.CharField(blank=True, default='NA', max_length=50),
        ),
    ]
